#!/usr/bin/env bash

TMPFILE=$(mktemp)

error() {
	CODE=$?
	if [ $CODE -eq 0 ]; then
		echo "pass"
	else
		echo "FAIL: $CODE"
	fi
}

VIM_ARGS=""
bvim() {
	vim $VIM_ARGS $* +"noautocmd wq! ${TMPFILE}" &> /dev/null
	cat "${TMPFILE}"
}


# https://stackoverflow.com/a/28563534

cd "${0%/*}"
echo -n "Edit the text file without Hexmode ... "
[ "$(bvim uncompressed.txt)" == "$(cat uncompressed.txt)" ]; error

echo -n "Edit the text file with Hexmode ... "
[ "$(bvim -b uncompressed.txt)" == "$(xxd uncompressed.txt)" ]; error

echo -n "Edit the compressed file without Hexmode ... "
[ "$(bvim compressed.txt.gz)" == "$(gzip --uncompress --to-stdout compressed.txt.gz)" ]; error

echo -n "Edit the compressed file as binary. Again, gzip should win and no hex should be shown ... "
[ "$(bvim -b compressed.txt.gz)" == "$(gzip --uncompress --to-stdout compressed.txt.gz)" ]; error

echo -n "Edit a zip file without Hexmode ... "
[[ "$(bvim zipfile.zip)" =~ "zip.vim version" ]]; error

echo -n "Edit a zip file as binary. Zip plugin should win, no hex should be shown ... "
[[ "$(bvim -b zipfile.zip)" =~ "zip.vim version" ]]; error

echo -n "Edit a tar file without Hexmode ... "
[[ "$(bvim tarfile.tar)" =~ "tar.vim version" ]]; error

echo -n "Edit a tar file as binary. Tar plugin should win, no hex should be shown ... "
[[ "$(bvim -b tarfile.tar)" =~ "tar.vim version" ]]; error

echo -n "A binary file doesn't change when saved ... "
cp zipfile.zip binary-file
[ diff -q <(bvim -b binary-file) "zipfile.zip" &> /dev/null ]; error
rm binary-file

echo -n "An auto-detected binary file doesn't change when saved ... "
cp zipfile.zip binary-file
[ diff -q <(bvim -c "let g:hexmode_autodetect = 1" binary-file) "zipfile.zip" &> /dev/null ]; error
rm binary-file
